### PR TITLE
added support for scheduleLambdaFunction - Lambda Activities!

### PR DESCRIPTION
**Pull request by jwulf**

### CODE REVIEW

**Comment by jwulf** [comment]
Opened an issue: https://github.com/aws/aws-sdk-js/issues/682

**Comment by jwulf** [comment]
Works with aws-sdk@2.1.45

**Comment by ericabouaf** [comment]
@jwulf : Nice ! I've seen the news that swf now supports lambda activities, and wanted to implement it.

Is this version of the sdk available on lambda ?

**Comment by jwulf** [comment]
Yes, this works on Lambda.

On 17 Aug 2015, at 6:32 pm, Eric Abouaf notifications@github.com wrote:

@jwulf https://github.com/jwulf : Nice ! I've seen the news that swf now
supports lambda activities, and wanted to implement it.

Is this version of the sdk available on lambda ?

**Comment by ericabouaf** [comment]
I got the same "Unexpected key 'scheduleLambdaFunctionDecisionAttributes' found in params.decisions[0]" error while testing it...

Did you embed the 2.1.45 sdk within the lambda ?? What is your trick ?

**Comment by jwulf** [comment]
I'm using JAWS, and I just updated the package.json in there to aws-sdk: 2.1.45

**Pull request merged**
